### ISSUE TITLE
UI of settings window can be improved

### ISSUE THREAD

**Issue by idevkshitij** [duiqt/herta_kuru#87] opened 2023-07-12 17:43 UTC
Hey! In the settings pop up window the Title and Drop-Down text looks a bit cluttered with the close spacing.
I suggest to add a Delimiter for the same like " : " or " - " or any of your suggestions.
I would be happy to contribute the changes if you can assign it to me.

![image](https://github.com/duiqt/herta_kuru/assets/74612148/54ca775c-1579-4c16-b98c-fbc4d8449496)

**Comment by fred913** [comment] 2023-07-13 00:27
It should be solved in #88.

**Comment by idevkshitij** [comment] 2023-07-14 09:07
Oh I didn't see the opened issue earlier. Thus, raised one.

**Comment by fred913** [comment] 2023-07-14 09:33
Not your fault haha
I meant that I solved the issue according to your instructions.

**Comment by fred913** [comment] 2023-07-16 01:10
I'm going to close this if the problem is solved. If it's then not working as planned, reopening is also welcomed.

**Closed by fred913** 2023-07-16 01:10 UTC
