### ISSUE TITLE
Perhaps you should pay attention to safety

### ISSUE THREAD

**Issue by EnoshSAGIRI** [duiqt/herta_kuru#14] opened 2023-05-27 09:47 UTC
I can easily get the button in devtool by using JavaScript.And then I can use the loop function to repeatedly click the button a lot of times in a short time.Therefore, this will send a number of requests in a short time.Just like DDOS attacks but it's much weaker than that,lol.But too many times of loops will let the website crash,about one thousand clicks in one time.I don't know if this will put a huge burden on the server.

**Comment by fred913** [comment] 2023-05-27 11:55
The resources are actually stored on Github Pages, so neither the author nor you need to worry

**Comment by fred913** [comment] 2023-06-02 22:33
Duplicate of #10

**Closed by fred913** 2023-06-02 22:33 UTC
